repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["--ignore-words=codespell.txt"]
        exclude: '\\.terraform/|\\.terragrunt-cache/'
        files: '^aws/'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      #- id: check-added-large-files
      - id: fix-byte-order-marker
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: check-case-conflict
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: check-json
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: check-merge-conflict
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: check-symlinks
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: check-toml
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: check-xml
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: check-yaml
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: destroyed-symlinks
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: detect-private-key
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: end-of-file-fixer
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: forbid-new-submodules
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: trailing-whitespace
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: check-case-conflict
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: check-merge-conflict
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
      - id: debug-statements
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-fmt
        files: '^aws/.*\\.tf$'
        exclude: '\.terraform/|\.terragrunt-cache/'
      - id: terraform-validate
        files: '^aws/.*\\.tf$'
        exclude: '\.terraform/|\.terragrunt-cache/'
      # - id: tflint    # requires too much extra installation in GitHub Actions.
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.24.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-angular"]
        files: '^aws/'
        exclude: '\\.terraform/|\\.terragrunt-cache/'
ci:
  # for more information, see https://pre-commit.ci
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: quarterly
  skip:
    [
      terraform-fmt,
      helmlint,
      terraform-validate,
      tflint,
      shellcheck,
      markdown-link-check,
      commitlint,
    ]
  submodules: false
